#!/usr/bin/env python3
"""
organize_pipeline.py
Creates the complete 16-phase, 68-module pipeline folder structure
with relative symlinks to actual data files in output/.
"""

import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PIPELINE = ROOT / "pipeline"
OUTPUT = ROOT / "output"

stats = {"dirs_created": 0, "symlinks_created": 0, "missing_sources": []}


def ensure_dir(path):
    if not path.exists():
        path.mkdir(parents=True, exist_ok=True)
        stats["dirs_created"] += 1


def make_symlink(target: Path, link: Path):
    if link.is_symlink():
        link.unlink()
    if target.exists() or target.is_dir():
        rel = os.path.relpath(target, link.parent)
        os.symlink(rel, link)
        stats["symlinks_created"] += 1
    else:
        stats["missing_sources"].append(str(target))


def link_specific_files(data_dir: Path, output_subdir: str, files: list):
    src_dir = OUTPUT / output_subdir
    for f in files:
        make_symlink(src_dir / f, data_dir / f)


def link_all_data_files(data_dir: Path, output_subdir: str, prefix: str = ""):
    src_dir = OUTPUT / output_subdir
    if not src_dir.is_dir():
        stats["missing_sources"].append(str(src_dir))
        return
    for f in sorted(src_dir.iterdir()):
        if f.name in ("cache", "__pycache__", ".DS_Store", "checkpoint.json"):
            continue
        if f.is_dir():
            continue
        link_name = f"{prefix}{f.name}" if prefix else f.name
        make_symlink(f, data_dir / link_name)


def link_courses(d: Path):
    link_specific_files(d, "02_liste_courses", [
        "courses_normalisees.json", "partants_normalises.json"
    ])

def link_features(d: Path):
    link_specific_files(d, "features", [
        "features_matrix.csv", "features_matrix.json", "features_matrix.parquet"
    ])

def link_labels(d: Path):
    link_specific_files(d, "labels", [
        "labels.csv", "labels.json", "labels.parquet"
    ])

def link_rapports_merged(d: Path):
    link_specific_files(d, "rapports_merged", ["rapports_complets.json"])

def link_cotes(d: Path):
    link_specific_files(d, "07_cotes_marche", [
        "cotes_marche.csv", "cotes_marche.json", "cotes_marche.parquet"
    ])

def link_performances(d: Path):
    link_specific_files(d, "22_performances_detaillees", [
        "performances_detaillees.json"
    ])

def link_hippodromes(d: Path):
    make_symlink(ROOT / "hippodromes_db.py", d / "hippodromes_db.py")

def link_meteo(d: Path):
    link_specific_files(d, "13_meteo_historique", [
        "meteo_historique.csv", "meteo_historique.json", "meteo_historique.parquet"
    ])


def create_placeholder(data_dir: Path, name: str):
    sub = data_dir / name
    ensure_dir(sub)
    gitkeep = sub / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.touch()


def write_readme(data_dir: Path, lines: list):
    readme = data_dir / "README.txt"
    content = ["Data sources for this module:", "=" * 40, ""]
    for line in lines:
        content.append(f"  - {line}")
    content.append("")
    content.append("All paths are relative symlinks to output/.")
    content.append("Generated by organize_pipeline.py")
    readme.write_text("\n".join(content), encoding="utf-8")


def module_dir(phase: str, module_name: str) -> Path:
    d = PIPELINE / phase / module_name / "data"
    ensure_dir(d)
    return d


PHASE_NAMES = {
    1: "phase_01_infrastructure",
    2: "phase_02_feature_engineering",
    3: "phase_03_feature_selection",
    4: "phase_04_ml_core",
    5: "phase_05_deep_learning",
    6: "phase_06_advanced",
    7: "phase_07_automl",
    8: "phase_08_fusion",
    9: "phase_09_calibration",
    10: "phase_10_outsiders",
    11: "phase_11_betting",
    12: "phase_12_simulation",
    13: "phase_13_bet_sizing",
    14: "phase_14_adaptation",
    15: "phase_15_monitoring",
    16: "phase_16_orchestration",
}


def build_all():
    # ================================================================
    # PHASE 01: INFRASTRUCTURE
    # ================================================================
    P = "phase_01_infrastructure"

    d = module_dir(P, "01_data_ingestion_manager")
    link_courses(d)
    # Prefix 02b files to avoid name collision with 02 files
    for f in ["courses_normalisees.json", "courses_brut.json",
              "partants_normalises.json", "partants_brut.json"]:
        make_symlink(OUTPUT / "02b_scraper_letrot" / f, d / f"letrot_{f}")
    write_readme(d, [
        "02_liste_courses: courses_normalisees.json, partants_normalises.json",
        "02b_scraper_letrot: letrot_courses_*.json, letrot_partants_*.json",
    ])

    d = module_dir(P, "02_data_schema_validator")
    link_courses(d)
    write_readme(d, ["02_liste_courses: courses_normalisees.json, partants_normalises.json"])

    d = module_dir(P, "03_historical_dataset_builder")
    link_courses(d)
    link_all_data_files(d, "01_calendrier_reunions", prefix="calendrier_")
    link_specific_files(d, "16_nanaelie", [
        "nanaelie_2004_2013.csv", "nanaelie_2004_2013.json", "nanaelie_2004_2013.parquet"
    ])
    write_readme(d, ["02_liste_courses", "01_calendrier_reunions", "16_nanaelie"])

    d = module_dir(P, "04_data_quality_monitor")
    link_courses(d)
    write_readme(d, ["02_liste_courses"])

    d = module_dir(P, "05_missing_values_handler")
    link_courses(d)
    write_readme(d, ["02_liste_courses"])

    d = module_dir(P, "06_outlier_cleaner")
    link_courses(d)
    write_readme(d, ["02_liste_courses"])

    d = module_dir(P, "07_data_normalizer")
    link_courses(d)
    write_readme(d, ["02_liste_courses"])

    d = module_dir(P, "08_cache_manager")
    for sub in sorted(OUTPUT.iterdir()):
        cache_path = sub / "cache"
        if cache_path.is_dir():
            make_symlink(cache_path, d / f"cache_{sub.name}")
    write_readme(d, ["All cache directories from output/*/cache/"])

    # ================================================================
    # PHASE 02: FEATURE ENGINEERING
    # ================================================================
    P = "phase_02_feature_engineering"

    d = module_dir(P, "09_advanced_feature_generator")
    link_courses(d)
    link_features(d)
    write_readme(d, ["02_liste_courses", "features/ (matrix files)"])

    d = module_dir(P, "10_rolling_stats_generator")
    link_courses(d)
    link_specific_files(d, "05_historique_chevaux", [
        "historique_chevaux.csv", "historique_chevaux.json", "historique_chevaux.parquet"
    ])
    write_readme(d, ["02_liste_courses", "05_historique_chevaux"])

    d = module_dir(P, "11_temporal_feature_builder")
    link_courses(d)
    link_performances(d)
    link_meteo(d)
    write_readme(d, ["02_liste_courses", "22_performances_detaillees", "13_meteo_historique"])

    d = module_dir(P, "12_odds_feature_builder")
    link_cotes(d)
    link_specific_files(d, "27_citations_enjeux", ["citations_enjeux.json"])
    link_specific_files(d, "28_combinaisons_marche", ["combinaisons_marche.json"])
    write_readme(d, ["07_cotes_marche", "27_citations_enjeux", "28_combinaisons_marche"])

    d = module_dir(P, "13_jockey_trainer_synergy_builder")
    link_courses(d)
    link_all_data_files(d, "06_historique_jockeys")
    write_readme(d, ["02_liste_courses", "06_historique_jockeys"])

    d = module_dir(P, "14_pedigree_feature_builder")
    link_all_data_files(d, "08_pedigree", prefix="08_")
    link_specific_files(d, "14_pedigree", ["pedigrees.csv", "pedigrees.parquet"])
    link_specific_files(d, "12_pedigree", ["pedigrees_consolide.csv", "pedigrees_consolide.json"])
    link_specific_files(d, "36_pedigree_query", ["pedigree_query_data.json"])
    link_specific_files(d, "17_sire_ifce", [
        "chevaux_course.csv", "chevaux_course.json", "sire_stats.json"
    ])
    write_readme(d, ["08_pedigree", "14_pedigree", "12_pedigree", "36_pedigree_query", "17_sire_ifce"])

    d = module_dir(P, "15_track_bias_detector")
    link_courses(d)
    link_specific_files(d, "18_letrot_records", ["letrot_records.json"])
    link_specific_files(d, "19_boturfers_stats", [
        "boturfers_hippodromes.csv", "boturfers_hippodromes.json"
    ])
    link_hippodromes(d)
    link_meteo(d)
    write_readme(d, ["02_liste_courses", "18_letrot_records", "19_boturfers_stats",
                      "hippodromes_db.py", "13_meteo_historique"])

    d = module_dir(P, "16_pace_profile_builder")
    link_courses(d)
    link_specific_files(d, "11_sectionals", [
        "sectionals.csv", "sectionals.json", "sectionals.parquet"
    ])
    link_meteo(d)
    write_readme(d, ["02_liste_courses", "11_sectionals", "13_meteo_historique"])

    d = module_dir(P, "17_sectional_feature_builder")
    link_specific_files(d, "11_sectionals", [
        "sectionals.csv", "sectionals.json", "sectionals.parquet"
    ])
    write_readme(d, ["11_sectionals"])

    d = module_dir(P, "18_field_strength_builder")
    link_courses(d)
    link_specific_files(d, "field_strength", [
        "field_strength.csv", "field_strength.json", "field_strength.parquet"
    ])
    write_readme(d, ["02_liste_courses", "field_strength/"])

    # ================================================================
    # PHASE 03: FEATURE SELECTION
    # ================================================================
    P = "phase_03_feature_selection"

    d = module_dir(P, "19_selection_auto_features")
    link_features(d)
    write_readme(d, ["features/ (matrix files)"])

    d = module_dir(P, "20_feature_subset_optimizer")
    link_features(d)
    write_readme(d, ["features/ (matrix files)"])

    # ================================================================
    # PHASE 04: ML CORE (predictive models)
    # ================================================================
    P = "phase_04_ml_core"
    for num, name in [(21, "logistic_regression"), (22, "random_forest"),
                       (23, "xgboost"), (24, "lightgbm"), (25, "catboost")]:
        d = module_dir(P, f"{num:02d}_{name}")
        link_features(d)
        link_labels(d)
        write_readme(d, ["features/ (matrix files)", "labels/"])

    # ================================================================
    # PHASE 05: DEEP LEARNING (predictive models)
    # ================================================================
    P = "phase_05_deep_learning"
    for num, name, needs_perf in [
        (26, "mlp", True), (27, "lstm", True), (28, "gru", True),
        (29, "tabnet", False), (30, "tft", True)
    ]:
        d = module_dir(P, f"{num:02d}_{name}")
        link_features(d)
        link_labels(d)
        items = ["features/", "labels/"]
        if needs_perf:
            link_performances(d)
            items.append("22_performances_detaillees")
        write_readme(d, items)

    # ================================================================
    # PHASE 06: ADVANCED (predictive models)
    # ================================================================
    P = "phase_06_advanced"

    d = module_dir(P, "31_gnn")
    link_features(d); link_labels(d); link_courses(d)
    write_readme(d, ["features/", "labels/", "02_liste_courses"])

    for num, name in [(32, "bayesian_nn"), (33, "survival_model"), (34, "quantile_regressor")]:
        d = module_dir(P, f"{num:02d}_{name}")
        link_features(d); link_labels(d)
        write_readme(d, ["features/", "labels/"])

    # ================================================================
    # PHASE 07: AUTOML (predictive models)
    # ================================================================
    P = "phase_07_automl"
    for num, name in [(35, "autogluon"), (36, "tpot"), (37, "h2o")]:
        d = module_dir(P, f"{num:02d}_{name}")
        link_features(d); link_labels(d)
        write_readme(d, ["features/", "labels/"])

    # ================================================================
    # PHASE 08: FUSION (predictive models)
    # ================================================================
    P = "phase_08_fusion"

    d = module_dir(P, "38_stacking")
    link_features(d); link_labels(d)
    create_placeholder(d, "oof_predictions")
    write_readme(d, ["features/", "labels/", "oof_predictions/ (placeholder)"])

    d = module_dir(P, "39_blending")
    link_features(d); link_labels(d)
    write_readme(d, ["features/", "labels/"])

    d = module_dir(P, "40_meta_model")
    link_features(d); link_labels(d)
    write_readme(d, ["features/", "labels/"])

    # ================================================================
    # PHASE 09: CALIBRATION
    # ================================================================
    P = "phase_09_calibration"

    d = module_dir(P, "41_calibration_inter_blocs")
    link_labels(d)
    create_placeholder(d, "raw_predictions")
    write_readme(d, ["labels/", "raw_predictions/ (placeholder)"])

    d = module_dir(P, "42_platt_scaling")
    link_labels(d)
    write_readme(d, ["labels/"])

    d = module_dir(P, "43_isotonic_calibration")
    link_labels(d)
    write_readme(d, ["labels/"])

    # ================================================================
    # PHASE 10: OUTSIDERS
    # ================================================================
    P = "phase_10_outsiders"

    d = module_dir(P, "44_anomalie_detector")
    link_cotes(d); link_courses(d); link_features(d)
    write_readme(d, ["07_cotes_marche", "02_liste_courses", "features/"])

    d = module_dir(P, "45_retour_forme_hidden")
    link_performances(d); link_courses(d)
    write_readme(d, ["22_performances_detaillees", "02_liste_courses"])

    d = module_dir(P, "46_gan_turf")
    link_features(d); link_courses(d)
    write_readme(d, ["features/", "02_liste_courses"])

    # ================================================================
    # PHASE 11: BETTING
    # ================================================================
    P = "phase_11_betting"

    d = module_dir(P, "47_roi_predictor")
    link_rapports_merged(d)
    link_specific_files(d, "21_rapports_definitifs", ["rapports_definitifs.json"])
    write_readme(d, ["rapports_merged/", "21_rapports_definitifs"])

    d = module_dir(P, "48_value_hunter_rl")
    link_cotes(d); link_rapports_merged(d)
    write_readme(d, ["07_cotes_marche", "rapports_merged/"])

    d = module_dir(P, "49_meta_selector")
    link_features(d)
    write_readme(d, ["features/"])

    d = module_dir(P, "50_ZURI_OUTSIDER_ENGINE")
    link_cotes(d); link_courses(d); link_features(d)
    write_readme(d, ["07_cotes_marche", "02_liste_courses", "features/"])

    # ================================================================
    # PHASE 12: SIMULATION
    # ================================================================
    P = "phase_12_simulation"

    d = module_dir(P, "51_monte_carlo")
    link_courses(d)
    create_placeholder(d, "calibrated_probs")
    write_readme(d, ["02_liste_courses", "calibrated_probs/ (placeholder)"])

    d = module_dir(P, "52_race_simulation")
    link_courses(d)
    write_readme(d, ["02_liste_courses"])

    # ================================================================
    # PHASE 13: BET SIZING
    # ================================================================
    P = "phase_13_bet_sizing"

    d = module_dir(P, "53_bet_sizing_engine")
    link_rapports_merged(d)
    write_readme(d, ["rapports_merged/"])

    d = module_dir(P, "54_kelly_strategy")
    link_rapports_merged(d)
    write_readme(d, ["rapports_merged/"])

    d = module_dir(P, "55_fractional_kelly")
    link_rapports_merged(d)
    write_readme(d, ["rapports_merged/"])

    d = module_dir(P, "56_ticket_optimizer")
    link_rapports_merged(d)
    link_specific_files(d, "28_combinaisons_marche", ["combinaisons_marche.json"])
    write_readme(d, ["rapports_merged/", "28_combinaisons_marche"])

    d = module_dir(P, "57_tickets_combines")
    link_specific_files(d, "28_combinaisons_marche", ["combinaisons_marche.json"])
    link_rapports_merged(d)
    write_readme(d, ["28_combinaisons_marche", "rapports_merged/"])

    # ================================================================
    # PHASE 14: ADAPTATION
    # ================================================================
    P = "phase_14_adaptation"

    d = module_dir(P, "58_auto_recalibration")
    link_labels(d)
    create_placeholder(d, "predictions")
    write_readme(d, ["labels/", "predictions/ (placeholder)"])

    d = module_dir(P, "59_model_decay_detector")
    link_labels(d)
    write_readme(d, ["labels/"])

    d = module_dir(P, "60_concept_drift_detector")
    link_features(d); link_labels(d)
    write_readme(d, ["features/", "labels/"])

    # ================================================================
    # PHASE 15: MONITORING
    # ================================================================
    P = "phase_15_monitoring"

    d = module_dir(P, "61_telemetrie")
    create_placeholder(d, "logs")
    write_readme(d, ["logs/ (placeholder for telemetry logs)"])

    d = module_dir(P, "62_dashboard")
    link_rapports_merged(d); link_labels(d)
    write_readme(d, ["rapports_merged/", "labels/"])

    d = module_dir(P, "63_alert_manager")
    create_placeholder(d, "logs")
    write_readme(d, ["logs/ (placeholder for alert logs)"])

    # ================================================================
    # PHASE 16: ORCHESTRATION
    # ================================================================
    P = "phase_16_orchestration"

    d = module_dir(P, "64_orchestrateur")
    for i in range(1, 16):
        pname = PHASE_NAMES[i]
        phase_path = PIPELINE / pname
        if phase_path.is_dir():
            make_symlink(phase_path, d / pname)
    write_readme(d, ["Symlinks to all 15 other phase directories for orchestration"])

    d = module_dir(P, "65_workflow_dependency_manager")
    create_placeholder(d, "config")
    write_readme(d, ["config/ (placeholder for workflow dependency configs)"])

    d = module_dir(P, "66_job_scheduler")
    create_placeholder(d, "config")
    write_readme(d, ["config/ (placeholder for scheduler configs)"])

    d = module_dir(P, "67_multi_model_controller")
    create_placeholder(d, "config")
    write_readme(d, ["config/ (placeholder for model controller configs)"])

    d = module_dir(P, "68_failover_manager")
    create_placeholder(d, "logs")
    write_readme(d, ["logs/ (placeholder for failover logs)"])


def main():
    # Step 1: Remove existing pipeline/data/
    old_data = PIPELINE / "data"
    if old_data.exists():
        shutil.rmtree(old_data)
        print(f"[REMOVED] {old_data}")

    # Step 2: Build the full structure
    print(f"Project root: {ROOT}")
    print(f"Building 16-phase, 68-module pipeline structure...\n")
    build_all()

    # Step 3: Count modules
    module_count = 0
    phase_count = 0
    for phase_dir in sorted(PIPELINE.iterdir()):
        if phase_dir.is_dir() and phase_dir.name.startswith("phase_"):
            phase_count += 1
            for mod_dir in sorted(phase_dir.iterdir()):
                if mod_dir.is_dir():
                    module_count += 1

    # Step 4: Summary
    print("=" * 60)
    print("  PIPELINE STRUCTURE CREATION SUMMARY")
    print("=" * 60)
    print(f"  Phases:               {phase_count}")
    print(f"  Modules:              {module_count}")
    print(f"  Directories created:  {stats['dirs_created']}")
    print(f"  Symlinks created:     {stats['symlinks_created']}")

    missing = sorted(set(stats["missing_sources"]))
    if missing:
        print(f"\n  Missing sources ({len(missing)}):")
        for m in missing:
            print(f"    [MISSING] {m}")
    else:
        print("\n  All source files found!")
    print("=" * 60)


if __name__ == "__main__":
    main()
