#!/usr/bin/env python3
"""
organize_model_data.py
Creates model-specific data folders under pipeline/data/ with RELATIVE symlinks
pointing to actual data files in output/. No data is copied.

Each model type gets its own folder with all the data it needs.
"""

import os
import sys
from pathlib import Path

# ── Project root = directory containing this script ──────────────────────────
ROOT = Path(__file__).resolve().parent


# ── Helper functions ─────────────────────────────────────────────────────────

def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def make_relative_symlink(target: Path, link: Path):
    """
    Create a relative symlink at `link` pointing to `target`.
    Both paths must be absolute. The symlink value stored on disk
    will be the *relative* path from the link's parent to the target.
    """
    if link.exists() or link.is_symlink():
        link.unlink()

    target = target.resolve()
    if not target.exists():
        print(f"  [SKIP] target missing: {target}")
        return False

    rel = os.path.relpath(target, link.parent)
    os.symlink(rel, link)
    return True


def symlink_file(src_relative: str, dest_dir: Path, dest_name: str = None):
    """
    Symlink a single file.
    src_relative is relative to ROOT (e.g. 'output/features/features_matrix.json').
    """
    src = ROOT / src_relative
    name = dest_name or src.name
    link = dest_dir / name
    ok = make_relative_symlink(src, link)
    return (name, src_relative, ok)


def symlink_dir(src_relative: str, dest_dir: Path, dest_name: str = None):
    """Symlink an entire directory."""
    src = ROOT / src_relative
    name = dest_name or src.name
    link = dest_dir / name
    ok = make_relative_symlink(src, link)
    return (name, src_relative, ok)


def write_readme(dest_dir: Path, title: str, description: str, entries: list):
    """Write a README.txt listing what's in the folder."""
    lines = [
        f"{'=' * 60}",
        f"  {title}",
        f"{'=' * 60}",
        "",
        description,
        "",
        "Contents (symlinks to source):",
        "-" * 40,
    ]
    for name, source, ok in entries:
        status = "OK" if ok else "MISSING"
        lines.append(f"  {name:40s} <- {source}  [{status}]")

    lines += [
        "",
        "-" * 40,
        "All entries are SYMLINKS — no data is duplicated.",
        f"Generated by organize_model_data.py",
        "",
    ]
    (dest_dir / "README.txt").write_text("\n".join(lines), encoding="utf-8")


# ── Data folder definitions ─────────────────────────────────────────────────

def create_baseline_ml():
    d = ROOT / "pipeline" / "data" / "baseline_ml"
    ensure_dir(d)
    entries = []

    # Features matrix (all formats)
    for ext in ("json", "csv", "parquet"):
        entries.append(symlink_file(f"output/features/features_matrix.{ext}", d))

    # Labels directory
    entries.append(symlink_dir("output/labels", d, "labels"))

    # Courses & partants
    entries.append(symlink_file("output/02_liste_courses/courses_normalisees.json", d))
    entries.append(symlink_file("output/02_liste_courses/partants_normalises.json", d))

    # Rapports
    entries.append(symlink_file("output/21_rapports_definitifs/rapports_definitifs.json", d))
    entries.append(symlink_file("output/38_rapports_internet/rapports_internet.json", d))

    # Meteo
    entries.append(symlink_file("output/13_meteo_historique/meteo_historique.json", d))

    # Pedigree (both sources)
    entries.append(symlink_dir("output/14_pedigree", d, "pedigree_14"))
    entries.append(symlink_dir("output/08_pedigree", d, "pedigree_08"))

    # Hippodromes DB
    entries.append(symlink_file("hippodromes_db.py", d))

    write_readme(d, "BASELINE ML DATA",
                 "Shared tabular data for XGBoost, LightGBM, CatBoost, RandomForest, LogisticRegression.",
                 entries)
    return ("baseline_ml", d, entries)


def create_deep_learning():
    d = ROOT / "pipeline" / "data" / "deep_learning"
    ensure_dir(d)
    entries = []

    # Everything from baseline_ml (symlink to the baseline_ml folder itself)
    baseline = ROOT / "pipeline" / "data" / "baseline_ml"
    entries.append(("baseline_ml", "pipeline/data/baseline_ml",
                    make_relative_symlink(baseline, d / "baseline_ml")))

    # Performances detaillees — historical race sequences
    entries.append(symlink_file(
        "output/22_performances_detaillees/performances_detaillees.json", d))

    write_readme(d, "DEEP LEARNING DATA",
                 "For LSTM, GRU, TabNet, TFT.\n"
                 "Includes everything from baseline_ml/ PLUS temporal sequence data.\n"
                 "The baseline_ml/ symlink gives access to all tabular features.",
                 entries)
    return ("deep_learning", d, entries)


def create_stacking():
    d = ROOT / "pipeline" / "data" / "stacking"
    ensure_dir(d)
    entries = []

    # Feature matrix + labels
    entries.append(symlink_file("output/features/features_matrix.parquet", d))
    entries.append(symlink_dir("output/labels", d, "labels"))

    # OOF predictions directory (to be populated later)
    oof_dir = d / "oof_predictions"
    ensure_dir(oof_dir)
    (oof_dir / ".gitkeep").touch()
    entries.append(("oof_predictions/", "(generated later by base models)", True))

    write_readme(d, "STACKING / ENSEMBLE DATA",
                 "For stacking_ensemble, meta_selector.\n"
                 "OOF predictions will be generated by base model training.",
                 entries)
    return ("stacking", d, entries)


def create_market():
    d = ROOT / "pipeline" / "data" / "market"
    ensure_dir(d)
    entries = []

    entries.append(symlink_file("output/27_citations_enjeux/citations_enjeux.json", d))
    entries.append(symlink_file("output/28_combinaisons_marche/combinaisons_marche.json", d))
    entries.append(symlink_file("output/21_rapports_definitifs/rapports_definitifs.json", d))
    entries.append(symlink_file("output/38_rapports_internet/rapports_internet.json", d))

    # Cotes / odds
    for ext in ("json", "csv", "parquet"):
        entries.append(symlink_file(f"output/07_cotes_marche/cotes_marche.{ext}", d))

    write_readme(d, "MARKET / BETTING DATA",
                 "For betting optimization, value detection.\n"
                 "Contains market citations, odds, combinations, and official reports.",
                 entries)
    return ("market", d, entries)


def create_calibration():
    d = ROOT / "pipeline" / "data" / "calibration"
    ensure_dir(d)
    entries = []

    # Raw predictions placeholder
    pred_dir = d / "raw_predictions"
    ensure_dir(pred_dir)
    (pred_dir / ".gitkeep").touch()
    entries.append(("raw_predictions/", "(generated later by trained models)", True))

    # Labels for calibration evaluation
    entries.append(symlink_dir("output/labels", d, "labels"))

    write_readme(d, "CALIBRATION DATA",
                 "For Platt scaling, Isotonic regression, Temperature scaling.\n"
                 "Raw model predictions will be generated after model training.",
                 entries)
    return ("calibration", d, entries)


def create_monte_carlo():
    d = ROOT / "pipeline" / "data" / "monte_carlo"
    ensure_dir(d)
    entries = []

    # Calibrated probabilities placeholder
    prob_dir = d / "calibrated_probabilities"
    ensure_dir(prob_dir)
    (prob_dir / ".gitkeep").touch()
    entries.append(("calibrated_probabilities/", "(generated later by calibration)", True))

    # Course data for simulation context
    entries.append(symlink_file("output/02_liste_courses/courses_normalisees.json", d))
    entries.append(symlink_file("output/02_liste_courses/partants_normalises.json", d))

    write_readme(d, "MONTE CARLO DATA",
                 "For race simulation.\n"
                 "Calibrated probabilities will be generated after calibration step.",
                 entries)
    return ("monte_carlo", d, entries)


def create_outsider():
    d = ROOT / "pipeline" / "data" / "outsider"
    ensure_dir(d)
    entries = []

    # Model probabilities placeholder
    prob_dir = d / "model_probabilities"
    ensure_dir(prob_dir)
    (prob_dir / ".gitkeep").touch()
    entries.append(("model_probabilities/", "(generated later by models)", True))

    # Market odds
    for ext in ("json", "csv", "parquet"):
        entries.append(symlink_file(f"output/07_cotes_marche/cotes_marche.{ext}", d))

    # Form data (performances)
    entries.append(symlink_file(
        "output/22_performances_detaillees/performances_detaillees.json", d))
    entries.append(symlink_file("output/02_liste_courses/partants_normalises.json", d))

    write_readme(d, "OUTSIDER DETECTION DATA",
                 "For anomaly detection / outsider spotting.\n"
                 "Model probabilities + market odds + form data.",
                 entries)
    return ("outsider", d, entries)


def create_turf():
    d = ROOT / "pipeline" / "data" / "turf"
    ensure_dir(d)
    entries = []

    entries.append(symlink_file("output/02_liste_courses/partants_normalises.json", d))
    entries.append(symlink_file("output/02_liste_courses/courses_normalisees.json", d))

    # Equipment data
    entries.append(symlink_dir("output/09_equipements", d, "equipements"))

    # Poids / handicaps
    entries.append(symlink_dir("output/10_poids_handicaps", d, "poids_handicaps"))

    write_readme(d, "DOMAIN / TURF DATA",
                 "For musique decoder, equipment parser, handicap analysis.\n"
                 "Core partants + courses + equipment + handicap data.",
                 entries)
    return ("turf", d, entries)


def create_post_course():
    d = ROOT / "pipeline" / "data" / "post_course"
    ensure_dir(d)
    entries = []

    # Predictions + actuals placeholders
    for name in ("predictions", "actuals"):
        sub = d / name
        ensure_dir(sub)
        (sub / ".gitkeep").touch()
        entries.append((f"{name}/", "(generated later)", True))

    # Labels (actual outcomes)
    entries.append(symlink_dir("output/labels", d, "labels"))

    # Rapports for result verification
    entries.append(symlink_file("output/21_rapports_definitifs/rapports_definitifs.json", d))

    write_readme(d, "POST-COURSE DATA",
                 "For drift detection, model decay monitoring, feedback loops.\n"
                 "Predictions and actuals will be populated after inference runs.",
                 entries)
    return ("post_course", d, entries)


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print(f"Project root: {ROOT}")
    print(f"Creating model data folders under: pipeline/data/\n")

    creators = [
        create_baseline_ml,
        create_deep_learning,
        create_stacking,
        create_market,
        create_calibration,
        create_monte_carlo,
        create_outsider,
        create_turf,
        create_post_course,
    ]

    all_results = []
    for fn in creators:
        result = fn()
        all_results.append(result)

    # ── Summary ──────────────────────────────────────────────────────────
    print("=" * 60)
    print("  SUMMARY")
    print("=" * 60)

    total_links = 0
    total_ok = 0
    total_missing = 0

    for name, path, entries in all_results:
        ok = sum(1 for _, _, s in entries if s)
        missing = sum(1 for _, _, s in entries if not s)
        total_links += len(entries)
        total_ok += ok
        total_missing += missing

        status = "OK" if missing == 0 else f"{missing} MISSING"
        rel_path = path.relative_to(ROOT)
        print(f"  {rel_path!s:40s}  {ok:2d} links  [{status}]")

    print("-" * 60)
    print(f"  Total: {total_links} links ({total_ok} OK, {total_missing} missing)")
    print(f"  All folders use RELATIVE symlinks — no data duplicated.")
    print(f"  Disk overhead: ~0 bytes (symlinks only).")
    print()


if __name__ == "__main__":
    main()
